### ISSUE TITLE
Problem with 12.4.1

### ISSUE THREAD

**Issue by vit37** [ziasam/ProtonKnockOff-Release#2]
Updated the firmware to 12.4.1. After booting into the system, I get a lot of application errors, IMEI flew off, bluetotth wifi
Now I'm looking at the link to download this firmware was removed.
Can I put 12.4.0 on top to roll back?

**Comment by ziasam** [comment]
Yeah just flash old build asap

**Comment by ziasam** [comment]
Fix build will come soon

**Comment by ziasam** [comment]
> Updated the firmware to 12.4.1. After booting into the system, I get a lot of application errors, IMEI flew off, bluetotth wifi Now I'm looking at the link to download this firmware was removed. Can I put 12.4.0 on top to roll back?

Fixed and Released new build.
